In [30]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

import statsmodels.api as sm
from statsmodels.formula.api import glm

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import f1_score
from math import sqrt

from sklearn import tree
from sklearn.utils import shuffle
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn.metrics import accuracy_score,recall_score,f1_score,precision_score
from sklearn.metrics import confusion_matrix

from sklearn import metrics

In [4]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - Copy.csv')

In [5]:
df.head()

,SA1_CODE21,tripDensity,date,hour,trainDensity,busDensity,tramDensity,House perc,Cafe perc,Office perc,...,15-29 %,30-39 %,40-49 %,50-64 %,above65 %,female%,male%,Population density 2021,rainfall,min_temp
0,20604111702,0,1,0,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
1,20604111702,0,1,1,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
2,20604111702,19,1,2,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
3,20604111702,0,1,3,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
4,20604111702,0,1,4,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4

In [4]:
#df['tripDensity'].quantile(0.8)

In [5]:
#SA_list=df.sort_values('tripDensity',ascending = False)['SA1_CODE21'].unique()

In [6]:
#selected_SA=SA_list[0:300]

In [7]:
#df=df.groupby('SA1_CODE21').filter(lambda g: g['SA1_CODE21'].isin(selected_SA).any())

In [6]:
column=['tripDensity']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,House perc,Cafe perc,Office perc,Shops perc,...,15-29 %,30-39 %,40-49 %,50-64 %,above65 %,female%,male%,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,20604151016,7,19,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56612,20604151016,7,20,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56613,20604151016,7,21,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56614,20604151016,7,22,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56615,20604151016,7,23,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0

In [7]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [8]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)

In [9]:
df_depe["date"].replace({1:1,2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)

In [10]:
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [11]:
categorical =['hour','date','rainfall','trainDensity']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')

In [12]:
#df=pd.get_dummies(df, drop_first=True )

df_depe=pd.get_dummies(df_depe, drop_first=True)

In [13]:
df_depe.columns

Index(['busDensity', 'tramDensity', 'House perc', 'Cafe perc', 'Office perc',
       'Shops perc', 'entropy', 'mxi', 'recreationCount', 'campusCount',
       '5-14 %', '15-29 %', '30-39 %', '40-49 %', '50-64 %', 'above65 %',
       'female%', 'male%', 'Population density 2021', 'min_temp', 'date_2',
       'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8',
       'trainDensity_1', 'rainfall_1'],
      dtype='object')

In [14]:
scale= StandardScaler()

In [15]:
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [16]:
df_sc

,busDensity,tramDensity,House perc,Cafe perc,Office perc,Shops perc,entropy,mxi,recreationCount,campusCount,...,date_2,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,trainDensity_1,rainfall_1
0,0.315978,0.018011,0.033479,-0.078797,0.030506,0.859859,1.68699,-2.020967,-0.1895,-0.109599,...,-0.632456,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.165647,-1.581139
1,0.315978,0.018011,0.033479,-0.078797,0.030506,0.859859,1.68699,-2.020967,-0.1895,-0.109599,...,-0.632456,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.165647,-1.581139
2,0.315978,0.018011,0.033479,-0.078797,0.030506,0.859859,1.68699,-2.020967,-0.1895,-0.109599,...,-0.632456,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.165647,-1.581139
3,0.315978,0.018011,0.033479,-0.078797,0.030506,0.859859,1.68699,-2.020967,-0.1895,-0.109599,...,-0.632456,2.645751,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.165647,-1.581139
4,0.315978,0.018011,0.033479,-0.078797,0.030506,0.859859,1.68699,-2.020967,-0.1895,-0.109599,...,-0.632456,2.645751,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.165647,-1.581139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,0.456568,-0.462221,-0.666664,0.487302,0.786520,1.037031,1.18977,0.050337,-0.1895,-0.109599,...,1.581139,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.377964,-0.165647,0.632456
56612,0.456568,-0.462221,-0.666664,0.487302,0.786520,1.037031,1.18977,0.050337,-0.1895,-0.109599,...,1.581139,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.377964,-0.165647,0.632456
56613,0.456568,-0.462221,-0.666664,0.487302,0.786520,1.037031,1.18977,0.050337,-0.1895,-0.109599,...,1.581139,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.165647,0.632456
56614,0.456568,-0.462221,-0.666664,0.487302,0.786520,1.037031,1.18977,0.050337,-0.1895,-0.109599,...,1.581139,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.165647,0.632456
56615,0.456568,-0.462221,-0.666664,0.487302,0.786520,1.037031,1.18977,0.050337,-0.1895,-0.109599,...,1.581139,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.165647,0.632456

In [17]:
df['tripDensity'] = df['tripDensity'].map(lambda x: 1 if x>49.0 else 0)
df['tripDensity']=df['tripDensity'].astype('category')

In [18]:
y=df['tripDensity']
X=df_sc

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=24)

In [20]:
clf = LogisticRegression(C=1,random_state=42,max_iter=1000)

In [21]:
model = clf.fit(X_train, y_train)

In [22]:
ypredict_train = clf.predict(X_train)

In [23]:
acc = accuracy_score(y_train,ypredict_train)
acc

0.8127483882363331

In [24]:
ypredict = clf.predict(X_test)

In [25]:
acc = accuracy_score(y_test,ypredict)
acc

0.8165842458495232

In [28]:
cnf_matrix = confusion_matrix(y_test,ypredict)

In [26]:
mean_squared_error(y_test,ypredict)

0.18341575415047687

In [30]:
print(clf.coef_)

[[-0.08838533  0.19455509 -0.86349918 -0.45959311  0.04001657  0.05019029
  -0.17572287  0.00960024 -0.21822998 -0.01916406 -0.33195372  0.24491638
  -0.3873639   0.0783082   0.32786563 -0.38167108 -0.35637778  0.35637778
   0.14876855  0.18050248  0.39522751 -0.28289631 -0.17119382  0.01845598
   0.13871368  0.23660068  0.18980316  0.18281499 -0.04745575 -0.14315578]]

In [27]:
y_pred_proba = clf.predict_proba(X_test)[::,1]

In [28]:
auc = metrics.roc_auc_score(y_test, y_pred_proba)

In [29]:
print(auc)

0.7847760606450833

In [32]:
f1 = accuracy_score(y_test,ypredict)
f1

0.8165842458495232

In [ ]:
#######################################################################################

In [44]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [45]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - Copy.csv')

In [46]:
column=['tripDensity']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,House perc,Cafe perc,Office perc,Shops perc,...,15-29 %,30-39 %,40-49 %,50-64 %,above65 %,female%,male%,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,20604151016,7,19,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56612,20604151016,7,20,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56613,20604151016,7,21,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56614,20604151016,7,22,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56615,20604151016,7,23,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0

In [47]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [48]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)
df_depe["date"].replace({1:1,2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [49]:
categorical =['hour','date','rainfall','trainDensity']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')

In [50]:
df_depe=pd.get_dummies(df_depe, drop_first=True)

In [51]:
df_depe.columns

Index(['busDensity', 'tramDensity', 'House perc', 'Cafe perc', 'Office perc',
       'Shops perc', 'entropy', 'mxi', 'recreationCount', 'campusCount',
       '5-14 %', '15-29 %', '30-39 %', '40-49 %', '50-64 %', 'above65 %',
       'female%', 'male%', 'Population density 2021', 'min_temp', 'date_2',
       'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8',
       'trainDensity_1', 'rainfall_1'],
      dtype='object')

In [52]:
scale= StandardScaler()

In [53]:
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [54]:
df['tripDensity'] = df['tripDensity'].map(lambda x: 1 if x>49.0 else 0)
df['tripDensity']=df['tripDensity'].astype('category')

In [55]:
y=df['tripDensity']
X=df_sc

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [58]:
len(X_test)

11324

In [59]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1,random_state=42,max_iter=1000)

In [60]:
model = clf.fit(X_train, y_train)

In [61]:
cdf = pd.DataFrame(model.coef_[0], index=X_train.columns, columns=['coefficients'])
cdf

                         coefficients
busDensity                  -0.105098
tramDensity                  0.196375
House perc                  -0.823428
Cafe perc                   -0.434700
Office perc                  0.047546
Shops perc                   0.062122
entropy                     -0.171970
mxi                          0.017854
recreationCount             -0.185826
campusCount                 -0.029446
5-14 %                      -0.343025
15-29 %                      0.244710
30-39 %                     -0.394852
40-49 %                      0.095656
50-64 %                      0.328167
above65 %                   -0.379377
female%                     -0.351599
male%                        0.351599
Population density 2021      0.142594
min_temp                     0.187937
date_2                       0.385784
hour_2                      -0.295284
hour_3                      -0.167026
hour_4                       0.013668
hour_5                       0.126814
hour_6                       0.241900
hour_7                       0.189190
hour_8                       0.189459
trainDensity_1              -0.057985
rainfall_1                  -0.133450

In [62]:
ypredict = clf.predict(X_test)

In [65]:
from sklearn import metrics
metrics.mean_absolute_error(y_test, ypredict)

0.18297421405863654

In [66]:
import numpy
numpy.sqrt(metrics.mean_squared_error(y_test, ypredict))

0.4277548527587227

In [75]:
metrics.accuracy_score(y_test, ypredict)

0.8170257859413634

In [76]:
metrics.f1_score(y_test, ypredict)

0.3032952252858103

In [77]:
y_pred_proba = clf.predict_proba(X_test)[::,1]
auc = metrics.roc_auc_score(y_test, y_pred_proba)
print(auc)

0.7941462154010527

In [71]:
import statsmodels.api as sm

In [68]:
X_train =sm.add_constant(X_train)

In [72]:
model=sm.Logit(y_train,X_train)

In [73]:
result = model.fit()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.407391
         Iterations: 35

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)

In [74]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:            tripDensity   No. Observations:                45292
Model:                          Logit   Df Residuals:                    45262
Method:                           MLE   Df Model:                           29
Date:                Mon, 19 Sep 2022   Pseudo R-squ.:                  0.1842
Time:                        10:15:49   Log-Likelihood:                -18452.
converged:                      False   LL-Null:                       -22616.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -1.8700      0.018   -106.378      0.000      -1.904      -1.836
busDensity                 -0.1052      0.014     -7.268      0.000      -0.134      -0.077
tramDensity                 0.1964      0.015     12.807      0.000       0.166       0.226
House perc                 -0.8269      0.057    -14.442      0.000      -0.939      -0.715
Cafe perc                  -0.4381      0.056     -7.846      0.000      -0.548      -0.329
Office perc                 0.0471      0.014      3.365      0.001       0.020       0.074
Shops perc                  0.0619      0.012      5.124      0.000       0.038       0.086
entropy                    -0.1723      0.025     -6.778      0.000      -0.222      -0.122
mxi                         0.0174      0.028      0.624      0.533      -0.037       0.072
recreationCount            -0.1861      0.029     -6.422      0.000      -0.243      -0.129
campusCount                -0.0294      0.013     -2.223      0.026      -0.055      -0.003
5-14 %                     -0.2657        nan        nan        nan         nan         nan
15-29 %                     0.7501        nan        nan        nan         nan         nan
30-39 %                    -0.1897        nan        nan        nan         nan         nan
40-49 %                     0.2079        nan        nan        nan         nan         nan
50-64 %                     0.5068        nan        nan        nan         nan         nan
above65 %                  -0.1559        nan        nan        nan         nan         nan
female%                    -0.3520   3.57e+06  -9.87e-08      1.000   -6.99e+06    6.99e+06
male%                       0.3520   3.57e+06   9.87e-08      1.000   -6.99e+06    6.99e+06
Population density 2021     0.1427      0.028      5.036      0.000       0.087       0.198
min_temp                    0.1881      0.018     10.322      0.000       0.152       0.224
date_2                      0.3861      0.020     19.668      0.000       0.348       0.425
hour_2                     -0.2953      0.020    -14.502      0.000      -0.335      -0.255
hour_3                     -0.1670      0.019     -8.874      0.000      -0.204      -0.130
hour_4                      0.0137      0.018      0.784      0.433      -0.021       0.048
hour_5                      0.1269      0.017      7.528      0.000       0.094       0.160
hour_6                      0.2420      0.017     14.663      0.000       0.210       0.274
hour_7                      0.1893      0.017     11.355      0.000       0.157       0.222
hour_8                      0.1896      0.017     11.376      0.000       0.157       0.222
trainDensity_1             -0.0579      0.015     -3.765      0.000      -0.088      -0.028
rainfall_1                 -0.1336      0.015     -8.639      0.000      -0.164      -0.103
===========================================================================================
"""

#### correlated feature removed

In [100]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - removed_female_50-64_40-49_house.csv')

In [101]:
column=['tripDensity']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,Cafe perc,Office perc,Shops perc,entropy,...,recreationCount,campusCount,5-14 %,15-29 %,30-39 %,above65 %,male%,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,20604151016,7,19,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56612,20604151016,7,20,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56613,20604151016,7,21,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56614,20604151016,7,22,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56615,20604151016,7,23,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0

In [102]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [103]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)
df_depe["date"].replace({1:1,2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [104]:
categorical =['hour','date','rainfall','trainDensity']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')

In [105]:
df_depe=pd.get_dummies(df_depe, drop_first=True)
df_depe.columns

Index(['busDensity', 'tramDensity', 'Cafe perc', 'Office perc', 'Shops perc',
       'entropy', 'mxi', 'recreationCount', 'campusCount', '5-14 %', '15-29 %',
       '30-39 %', 'above65 %', 'male%', 'Population density 2021', 'min_temp',
       'date_2', 'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7',
       'hour_8', 'trainDensity_1', 'rainfall_1'],
      dtype='object')

In [106]:
scale= StandardScaler()
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [107]:
df['tripDensity'] = df['tripDensity'].map(lambda x: 1 if x>49.0 else 0)
df['tripDensity']=df['tripDensity'].astype('category')

In [108]:
y=df['tripDensity']
X=df_sc

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [110]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=1,random_state=42,max_iter=1000)

In [111]:
model = clf.fit(X_train, y_train)

In [112]:
ypredict = clf.predict(X_test)

In [113]:
from sklearn import metrics
metrics.mean_absolute_error(y_test, ypredict)

0.18209113387495585

In [114]:
import numpy
numpy.sqrt(metrics.mean_squared_error(y_test, ypredict))

0.42672137733532384

In [115]:
metrics.accuracy_score(y_test, ypredict)

0.8179088661250442

In [116]:
metrics.f1_score(y_test, ypredict)

0.29768392370572205

In [117]:
y_pred_proba = clf.predict_proba(X_test)[::,1]
auc = metrics.roc_auc_score(y_test, y_pred_proba)
print(auc)

0.7893516893546624

In [118]:
import statsmodels.api as sm
X_train =sm.add_constant(X_train)

In [119]:
model=sm.Logit(y_train,X_train)

In [120]:
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.408887
         Iterations 7

In [121]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:            tripDensity   No. Observations:                45292
Model:                          Logit   Df Residuals:                    45265
Method:                           MLE   Df Model:                           26
Date:                Mon, 19 Sep 2022   Pseudo R-squ.:                  0.1807
Time:                        11:02:42   Log-Likelihood:                -18519.
converged:                       True   LL-Null:                       -22604.
Covariance Type:            nonrobust   LLR p-value:                     0.000
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -1.8680      0.018   -105.849      0.000      -1.903      -1.833
busDensity                 -0.0644      0.014     -4.502      0.000      -0.092      -0.036
tramDensity                 0.1728      0.015     11.365      0.000       0.143       0.203
Cafe perc                   0.3401      0.016     21.006      0.000       0.308       0.372
Office perc                 0.1624      0.011     14.145      0.000       0.140       0.185
Shops perc                  0.1019      0.011      8.903      0.000       0.079       0.124
entropy                    -0.0890      0.024     -3.653      0.000      -0.137      -0.041
mxi                         0.0970      0.028      3.517      0.000       0.043       0.151
recreationCount            -0.1794      0.029     -6.260      0.000      -0.236      -0.123
campusCount                -0.0271      0.013     -2.015      0.044      -0.053      -0.001
5-14 %                     -0.5335      0.036    -14.892      0.000      -0.604      -0.463
15-29 %                    -0.6888      0.073     -9.432      0.000      -0.832      -0.546
30-39 %                    -0.8215      0.050    -16.481      0.000      -0.919      -0.724
above65 %                  -0.8831      0.085    -10.379      0.000      -1.050      -0.716
male%                       0.6799      0.047     14.610      0.000       0.589       0.771
Population density 2021     0.1609      0.027      5.856      0.000       0.107       0.215
min_temp                    0.1858      0.018     10.210      0.000       0.150       0.221
date_2                      0.3908      0.020     19.977      0.000       0.352       0.429
hour_2                     -0.2983      0.020    -14.658      0.000      -0.338      -0.258
hour_3                     -0.1731      0.019     -9.173      0.000      -0.210      -0.136
hour_4                      0.0089      0.017      0.510      0.610      -0.025       0.043
hour_5                      0.1240      0.017      7.399      0.000       0.091       0.157
hour_6                      0.2296      0.016     13.947      0.000       0.197       0.262
hour_7                      0.1828      0.017     11.030      0.000       0.150       0.215
hour_8                      0.1816      0.017     10.947      0.000       0.149       0.214
trainDensity_1             -0.0428      0.015     -2.844      0.004      -0.072      -0.013
rainfall_1                 -0.1328      0.015     -8.621      0.000      -0.163      -0.103
===========================================================================================
"""