In [1]:
import pandas as pd
import numpy as np

from patsy import dmatrices

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.formula.api import glm

from sklearn.metrics import mean_squared_error
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from math import sqrt

In [34]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - Copy.csv')

In [35]:
trip=df['tripDensity']

In [42]:

n=len(trip)
mean =sum(trip)/n
deviations = [(x-mean)**2 for x in trip]
variance = sum(deviations)/n
print("variance: "+str(variance)+"         mean: "+str(mean))

variance: 17438.122053694427         mean: 42.66101455418963

In [2]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - Copy.csv')

In [3]:
df.head()

,SA1_CODE21,tripDensity,date,hour,trainDensity,busDensity,tramDensity,House perc,Cafe perc,Office perc,...,15-29 %,30-39 %,40-49 %,50-64 %,above65 %,female%,male%,Population density 2021,rainfall,min_temp
0,20604111702,0,1,0,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
1,20604111702,0,1,1,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
2,20604111702,19,1,2,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
3,20604111702,0,1,3,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4
4,20604111702,0,1,4,0.0,38.68472,19.34236,0.370229,0.576336,0.022901,...,53.39985,19.330746,7.422579,8.152377,8.15831,50.488429,49.511571,9456.2,0,7.4

In [4]:
column=['tripDensity']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,House perc,Cafe perc,Office perc,Shops perc,...,15-29 %,30-39 %,40-49 %,50-64 %,above65 %,female%,male%,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,20604151016,7,19,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56612,20604151016,7,20,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56613,20604151016,7,21,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56614,20604151016,7,22,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56615,20604151016,7,23,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0

In [5]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [6]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)

In [7]:
df_depe["date"].replace({1:1, 2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)

In [8]:
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [9]:
categorical =['hour','date','rainfall','trainDensity']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')

In [10]:
#df=pd.get_dummies(df, drop_first=True )
df_depe=pd.get_dummies(df_depe, drop_first=True)

In [11]:
df_depe.columns

Index(['busDensity', 'tramDensity', 'House perc', 'Cafe perc', 'Office perc',
       'Shops perc', 'entropy', 'mxi', 'recreationCount', 'campusCount',
       '5-14 %', '15-29 %', '30-39 %', '40-49 %', '50-64 %', 'above65 %',
       'female%', 'male%', 'Population density 2021', 'min_temp', 'date_2',
       'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8',
       'trainDensity_1', 'rainfall_1'],
      dtype='object')

In [12]:
scale= StandardScaler()

In [13]:
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [14]:
y=df['tripDensity']
X=df_sc

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=24)

In [16]:
len(X_train)

45292

In [17]:
len(X_test)

11324

In [18]:
nb_training_results=sm.GLM(y_train,X_train, family=sm.families.NegativeBinomial(alpha=1)).fit(method='bfgs')
print(nb_training_results.summary())

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:512: RuntimeWarning: overflow encountered in true_divide
  score_factor = (self.endog - mu) / self.family.link.deriv(mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\varfuncs.py:265: RuntimeWarning: overflow encountered in square
  return p + self.alpha*p**2
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:513: RuntimeWarning: invalid value encountered in true_divide
  score_factor /= self.family.variance(mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\links.py:516: RuntimeWarning: overflow encountered in exp
  return np.exp(z)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:1394: RuntimeWarning: invalid value encountered in multiply
  ll_obs = endog * np.log(self.alpha * mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:1395: RuntimeWarning: invalid value encountered in subtract
  ll_obs -= (endog + 1 / self.alpha) * np.log(1 + self.alpha * mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:1394: RuntimeWarning: divide by zero encountered in log
  ll_obs = endog * np.log(self.alpha * mu)

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:            tripDensity   No. Observations:                45292
Model:                            GLM   Df Residuals:                    45263
Model Family:        NegativeBinomial   Df Model:                           28
Link Function:                    Log   Scale:                          1.0000
Method:                          bfgs   Log-Likelihood:            -1.3054e+07
Date:                Mon, 19 Sep 2022   Deviance:                   5.9480e+07
Time:                        17:32:18   Pearson chi2:                 1.03e+22
No. Iterations:                     0   Pseudo R-squ. (CS):        -1.564e+246
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
busDensity                  4.4582      0.026    169.063      0.000       4.407       4.510
tramDensity                -1.1585      0.006   -180.088      0.000      -1.171      -1.146
House perc                  0.4818   4.27e+05   1.13e-06      1.000   -8.37e+05    8.37e+05
Cafe perc                  -1.5212   4.27e+05  -3.56e-06      1.000   -8.38e+05    8.38e+05
Office perc                -2.2596   6.84e+04  -3.31e-05      1.000   -1.34e+05    1.34e+05
Shops perc                 -6.8042   3.11e+04     -0.000      1.000    -6.1e+04     6.1e+04
entropy                     5.7769      0.023    252.222      0.000       5.732       5.822
mxi                         0.2222      0.017     13.150      0.000       0.189       0.255
recreationCount            18.3925      2.393      7.685      0.000      13.702      23.083
campusCount                21.8670   1.52e+05      0.000      1.000   -2.98e+05    2.98e+05
5-14 %                  -3.648e+10        nan        nan        nan         nan         nan
15-29 %                 -2.375e+11        nan        nan        nan         nan         nan
30-39 %                 -9.689e+10        nan        nan        nan         nan         nan
40-49 %                 -5.258e+10        nan        nan        nan         nan         nan
50-64 %                 -8.385e+10        nan        nan        nan         nan         nan
above65 %               -1.051e+11        nan        nan        nan         nan         nan
female%                 -3345.1350        nan        nan        nan         nan         nan
male%                   -3340.6680        nan        nan        nan         nan         nan
Population density 2021   -35.2630   1.21e+04     -0.003      0.998   -2.37e+04    2.36e+04
min_temp                    0.1576      0.007     24.073      0.000       0.145       0.170
date_2                      1.3238      0.008    164.940      0.000       1.308       1.340
hour_2                      6.8098      0.683      9.974      0.000       5.472       8.148
hour_3                     -2.9128      0.011   -256.077      0.000      -2.935      -2.891
hour_4                     -2.2464      0.009   -253.436      0.000      -2.264      -2.229
hour_5                     -1.5594      0.008   -202.760      0.000      -1.574      -1.544
hour_6                     -1.1074      0.007   -158.641      0.000      -1.121      -1.094
hour_7                     -0.4467      0.007    -66.402      0.000      -0.460      -0.433
hour_8                     -0.7413      0.007   -109.196      0.000      -0.755      -0.728
trainDensity_1              9.1336   8757.674      0.001      0.999   -1.72e+04    1.72e+04
rainfall_1                  0.5287      0.006     90.338      0.000       0.517       0.540
===========================================================================================

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:512: RuntimeWarning: overflow encountered in true_divide
  score_factor = (self.endog - mu) / self.family.link.deriv(mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\varfuncs.py:265: RuntimeWarning: overflow encountered in square
  return p + self.alpha*p**2
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\generalized_linear_model.py:513: RuntimeWarning: invalid value encountered in true_divide
  score_factor /= self.family.variance(mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py:593: HessianInversionWarning: Inverting hessian failed, no bse or cov_params available
  'available', HessianInversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py:606: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  ConvergenceWarning)

In [19]:
nb_prediction_train=nb_training_results.get_prediction(X_train)
nb_summary_frame_train=nb_prediction_train.summary_frame()
print(nb_summary_frame_train)

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\regression\_prediction.py:61: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(self.var_pred_mean)

               mean       mean_se  mean_ci_lower  mean_ci_upper
6147   3.722268e+54  4.099495e+59   0.000000e+00            inf
4864   2.882062e+00  6.360929e-02   2.760048e+00   3.009469e+00
25971  1.682204e+07  3.472618e+07   2.942529e+05   9.616934e+08
15102  2.673296e+11  3.399532e+10   2.083545e+11   3.429977e+11
32708  1.156348e+08  9.109457e+06   9.909064e+07   1.349411e+08
...             ...           ...            ...            ...
21633  1.579939e+10  1.735348e+12   5.078137e-84  4.915596e+103
19857  4.416884e+10  2.031338e+12   3.148566e-29   6.196110e+49
14528  6.521259e+48  7.182144e+53   0.000000e+00            inf
899    1.459398e-10  1.251670e-11   1.233586e-10   1.726545e-10
45474  4.838324e+15  5.314241e+17   1.555184e-78  1.505249e+109

[45292 rows x 4 columns]

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\links.py:516: RuntimeWarning: overflow encountered in exp
  return np.exp(z)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\_prediction.py:45: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(self.var_pred_mean)

In [20]:
predicted_train_count=nb_summary_frame_train['mean']
predicted_train_count

6147     3.722268e+54
4864     2.882062e+00
25971    1.682204e+07
15102    2.673296e+11
32708    1.156348e+08
             ...
21633    1.579939e+10
19857    4.416884e+10
14528    6.521259e+48
899      1.459398e-10
45474    4.838324e+15
Name: mean, Length: 45292, dtype: float64

In [21]:
########### removed correlated

In [22]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - Copy.csv')

In [23]:
column=['tripDensity']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,House perc,Cafe perc,Office perc,Shops perc,...,15-29 %,30-39 %,40-49 %,50-64 %,above65 %,female%,male%,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.370229,0.576336,0.022901,0.030534,...,53.399850,19.330746,7.422579,8.152377,8.158310,50.488429,49.511571,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,20604151016,7,19,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56612,20604151016,7,20,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56613,20604151016,7,21,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56614,20604151016,7,22,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0
56615,20604151016,7,23,0.0,46.728972,0.00000,0.089286,0.803571,0.071429,0.035714,...,45.837792,34.053583,13.562667,0.000000,4.732242,48.352802,51.647198,9238.5,1,8.0

In [24]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [25]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)
df_depe["date"].replace({1:1, 2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [26]:
categorical =['date','trainDensity','hour']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')

In [27]:
#df=pd.get_dummies(df, drop_first=True )
df_depe=pd.get_dummies(df_depe, drop_first=True)

In [28]:
df_depe.columns

Index(['busDensity', 'tramDensity', 'House perc', 'Cafe perc', 'Office perc',
       'Shops perc', 'entropy', 'mxi', 'recreationCount', 'campusCount',
       '5-14 %', '15-29 %', '30-39 %', '40-49 %', '50-64 %', 'above65 %',
       'female%', 'male%', 'Population density 2021', 'rainfall', 'min_temp',
       'date_2', 'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7',
       'hour_8', 'trainDensity_1'],
      dtype='object')

In [29]:
scale= StandardScaler()

In [30]:
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [31]:
y=df['tripDensity']
X=df_sc

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=24)

In [33]:
nb_training_results=sm.GLM(y_train,X_train, family=sm.families.NegativeBinomial(alpha=1)).fit()
print(nb_training_results.summary())

C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:1342: RuntimeWarning: divide by zero encountered in true_divide
  endog_mu = self._clean(endog / mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:1342: RuntimeWarning: overflow encountered in true_divide
  endog_mu = self._clean(endog / mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:1342: RuntimeWarning: invalid value encountered in true_divide
  endog_mu = self._clean(endog / mu)
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\varfuncs.py:265: RuntimeWarning: overflow encountered in square
  return p + self.alpha*p**2
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\genmod\families\family.py:132: RuntimeWarning: invalid value encountered in multiply
  return 1. / (self.link.deriv(mu)**2 * self.variance(mu))

ValueError: NaN, inf or invalid value detected in weights, estimation infeasible.