In [1]:
import pandas as pd
import numpy as np

from patsy import dmatrices

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from statsmodels.formula.api import glm

from sklearn.metrics import mean_squared_error
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from math import sqrt

In [2]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\AllFeatures-original - wholeNumberDensity - removed_female_50-64_40-49_house - Copy.csv')

In [3]:
df.head()

,SA1_CODE21,tripDensity,date,hour,trainDensity,busDensity,tramDensity,Cafe perc,Office perc,Shops perc,...,recreationCount,campusCount,5-14 %,15-29 %,30-39 %,above65 %,male%,Population density 2021,rainfall,min_temp
0,20604111702,0,1,0,0.0,38.68472,19.34236,0.576336,0.022901,0.030534,...,0,0,3.536138,53.39985,19.330746,8.15831,49.511571,9456.2,0,7.4
1,20604111702,0,1,1,0.0,38.68472,19.34236,0.576336,0.022901,0.030534,...,0,0,3.536138,53.39985,19.330746,8.15831,49.511571,9456.2,0,7.4
2,20604111702,19,1,2,0.0,38.68472,19.34236,0.576336,0.022901,0.030534,...,0,0,3.536138,53.39985,19.330746,8.15831,49.511571,9456.2,0,7.4
3,20604111702,0,1,3,0.0,38.68472,19.34236,0.576336,0.022901,0.030534,...,0,0,3.536138,53.39985,19.330746,8.15831,49.511571,9456.2,0,7.4
4,20604111702,0,1,4,0.0,38.68472,19.34236,0.576336,0.022901,0.030534,...,0,0,3.536138,53.39985,19.330746,8.15831,49.511571,9456.2,0,7.4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56616 entries, 0 to 56615
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   SA1_CODE21               56616 non-null  int64
 1   tripDensity              56616 non-null  int64
 2   date                     56616 non-null  int64
 3   hour                     56616 non-null  int64
 4   trainDensity             56616 non-null  float64
 5   busDensity               56616 non-null  float64
 6   tramDensity              56616 non-null  float64
 7   Cafe perc                56616 non-null  float64
 8   Office perc              56616 non-null  float64
 9   Shops perc               56616 non-null  float64
 10  entropy                  56616 non-null  float64
 11  mxi                      56616 non-null  float64
 12  recreationCount          56616 non-null  int64
 13  campusCount              56616 non-null  int64
 14  5-14 %                   56616 non-null  float64
 15  15-29 %                  56616 non-null  float64
 16  30-39 %                  56616 non-null  float64
 17  above65 %                56616 non-null  float64
 18  male%                    56616 non-null  float64
 19  Population density 2021  56616 non-null  float64
 20  rainfall                 56616 non-null  int64
 21  min_temp                 56616 non-null  float64
dtypes: float64(15), int64(7)
memory usage: 9.5 MB

In [5]:
column=['tripDensity']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,Cafe perc,Office perc,Shops perc,entropy,...,recreationCount,campusCount,5-14 %,15-29 %,30-39 %,above65 %,male%,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,1.352866,...,0,0,3.536138,53.399850,19.330746,8.158310,49.511571,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56611,20604151016,7,19,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56612,20604151016,7,20,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56613,20604151016,7,21,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56614,20604151016,7,22,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0
56615,20604151016,7,23,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,1.118100,...,0,0,1.813717,45.837792,34.053583,4.732242,51.647198,9238.5,1,8.0

In [6]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [7]:
#df_depe=df_depe.drop(['female%'], axis=1)

In [7]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)

In [8]:
df_depe["date"].replace({1:1, 2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)

In [9]:
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [10]:
categorical =['hour','date','rainfall','trainDensity']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')
#df_depe['rainfall']=df_depe['rainfall'].astype('category')

In [11]:
#df=pd.get_dummies(df, drop_first=True )
df_depe=pd.get_dummies(df_depe, drop_first=True)

In [12]:
df_depe.columns

Index(['busDensity', 'tramDensity', 'Cafe perc', 'Office perc', 'Shops perc',
       'entropy', 'mxi', 'recreationCount', 'campusCount', '5-14 %', '15-29 %',
       '30-39 %', 'above65 %', 'male%', 'Population density 2021', 'min_temp',
       'date_2', 'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7',
       'hour_8', 'trainDensity_1', 'rainfall_1'],
      dtype='object')

In [16]:
scale= StandardScaler()

In [17]:
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [18]:
y=df['tripDensity']
X=df_sc

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=24)

In [20]:
len(X_train)

45292

In [21]:
y_train.isna().sum()

0

In [22]:
np.isfinite(y_train).all()
#np.isinf(df['15-29 %']).values.sum()

True

In [21]:
len(X_test)

11324

In [23]:
nb_training_results=sm.GLM(y_train,X_train, family=sm.families.NegativeBinomial(alpha=0.981766)).fit(method='bfgs')
print(nb_training_results.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:            tripDensity   No. Observations:                45292
Model:                            GLM   Df Residuals:                    45266
Model Family:        NegativeBinomial   Df Model:                           25
Link Function:                    Log   Scale:                          1.0000
Method:                          bfgs   Log-Likelihood:            -6.6351e+05
Date:                Tue, 20 Sep 2022   Deviance:                   1.1583e+06
Time:                        09:54:49   Pearson chi2:                 7.07e+08
No. Iterations:                     0   Pseudo R-squ. (CS):         -3.535e+08
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
busDensity                 -0.0352      0.002    -14.140      0.000      -0.040      -0.030
tramDensity                 0.2322      0.003     81.844      0.000       0.227       0.238
Cafe perc                   0.1694      0.002     68.180      0.000       0.165       0.174
Office perc                 0.0685      0.002     35.309      0.000       0.065       0.072
Shops perc                  0.1461      0.002     60.199      0.000       0.141       0.151
entropy                    -0.2817      0.004    -68.436      0.000      -0.290      -0.274
mxi                        -0.1852      0.005    -40.142      0.000      -0.194      -0.176
recreationCount            -0.2869      0.006    -50.948      0.000      -0.298      -0.276
campusCount                -0.1084      0.003    -40.268      0.000      -0.114      -0.103
5-14 %                     -0.2732      0.006    -43.175      0.000      -0.286      -0.261
15-29 %                    -0.5439      0.013    -40.880      0.000      -0.570      -0.518
30-39 %                    -1.3143      0.009   -140.689      0.000      -1.333      -1.296
above65 %                  -1.1391      0.018    -62.230      0.000      -1.175      -1.103
male%                       2.0206      0.010    212.069      0.000       2.002       2.039
Population density 2021     0.6726      0.006    107.983      0.000       0.660       0.685
min_temp                    0.1569      0.003     50.480      0.000       0.151       0.163
date_2                      0.4737      0.003    139.590      0.000       0.467       0.480
hour_2                     -0.4277      0.003   -140.721      0.000      -0.434      -0.422
hour_3                     -0.0383      0.003    -12.593      0.000      -0.044      -0.032
hour_4                      0.0389      0.003     13.089      0.000       0.033       0.045
hour_5                      0.1850      0.003     62.909      0.000       0.179       0.191
hour_6                      0.3275      0.003    110.854      0.000       0.322       0.333
hour_7                      0.2717      0.003     93.590      0.000       0.266       0.277
hour_8                      0.2530      0.003     88.657      0.000       0.247       0.259
trainDensity_1             -0.1712      0.003    -63.166      0.000      -0.177      -0.166
rainfall_1                 -0.1559      0.003    -58.521      0.000      -0.161      -0.151
===========================================================================================

In [24]:
nb_prediction_train=nb_training_results.get_prediction(X_train)
nb_summary_frame_train=nb_prediction_train.summary_frame()
print(nb_summary_frame_train)

            mean   mean_se  mean_ci_lower  mean_ci_upper
6147    0.026199  0.000365       0.025493       0.026924
4864   23.621387  0.232431      23.170195      24.081364
25971   1.466418  0.014901       1.437502       1.495916
15102   1.470329  0.017437       1.436546       1.504905
32708   1.453285  0.020604       1.413458       1.494233
...          ...       ...            ...            ...
21633   8.691651  0.083410       8.529698       8.856679
19857   3.996610  0.038406       3.922041       4.072597
14528   0.081655  0.001071       0.079582       0.083782
899     1.220486  0.014153       1.193061       1.248543
45474  25.850273  0.234853      25.394043      26.314700

[45292 rows x 4 columns]

In [25]:
predicted_train_count=nb_summary_frame_train['mean']
predicted_train_count

6147      0.026199
4864     23.621387
25971     1.466418
15102     1.470329
32708     1.453285
           ...
21633     8.691651
19857     3.996610
14528     0.081655
899       1.220486
45474    25.850273
Name: mean, Length: 45292, dtype: float64

In [26]:
ypredict = sm.GLM(y_train,X_train, family=sm.families.NegativeBinomial(alpha=0.981766)).predict(X_test)

ValueError: shapes (45292,26) and (11324,26) not aligned: 26 (dim 1) != 11324 (dim 0)