In [47]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.metrics import mean_absolute_error,mean_squared_error, accuracy_score,f1_score

import statsmodels.regression.mixed_linear_model as mlm

In [48]:
df=pd.read_csv(r'C:\Melbourne_Escooter\RealDataset\FinalResults\SA1\Features-trips\Final\final version\AllFeatures-original2.csv')

In [49]:
df.fillna(0, inplace=True)

In [50]:
column=['tripDensity','House perc','entropy','15-29 %','above65 %','female%','car owner %','male%','with no u 15 children sa1','with u 15 children sa1','no_childern Sa1']
df_depe=df.drop(column, axis=1)
df_depe

,SA1_CODE21,date,hour,trainDensity,busDensity,tramDensity,Cafe perc,Office perc,Shops perc,mxi,recreationCount,campusCount,5-14 %,30-39 %,40-49 %,50-64 %,Population density 2021,rainfall,min_temp
0,20604111702,1,0,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,12.977099,0,0,3.536138,19.330746,7.422579,8.152377,9456.2,0,7.4
1,20604111702,1,1,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,12.977099,0,0,3.536138,19.330746,7.422579,8.152377,9456.2,0,7.4
2,20604111702,1,2,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,12.977099,0,0,3.536138,19.330746,7.422579,8.152377,9456.2,0,7.4
3,20604111702,1,3,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,12.977099,0,0,3.536138,19.330746,7.422579,8.152377,9456.2,0,7.4
4,20604111702,1,4,0.0,38.684720,19.34236,0.576336,0.022901,0.030534,12.977099,0,0,3.536138,19.330746,7.422579,8.152377,9456.2,0,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56779,20604151016,7,19,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,41.071429,0,0,1.813717,34.053583,13.562667,0.000000,9238.5,1,8.0
56780,20604151016,7,20,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,41.071429,0,0,1.813717,34.053583,13.562667,0.000000,9238.5,1,8.0
56781,20604151016,7,21,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,41.071429,0,0,1.813717,34.053583,13.562667,0.000000,9238.5,1,8.0
56782,20604151016,7,22,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,41.071429,0,0,1.813717,34.053583,13.562667,0.000000,9238.5,1,8.0
56783,20604151016,7,23,0.0,46.728972,0.00000,0.803571,0.071429,0.035714,41.071429,0,0,1.813717,34.053583,13.562667,0.000000,9238.5,1,8.0

In [51]:
df_depe=df_depe.drop(['SA1_CODE21'], axis=1)

In [52]:
df_depe["hour"].replace({0:1,1:1,2:1,3:2,4:2,5:2,6:3,7:3,8:3,9:4,10:4,11:4,12:5,13:5,14:5,15:6,16:6,17:6,18:7,19:7,20:7,21:8,22:8,23:8}, inplace=True)

In [53]:
df_depe["date"].replace({1:1, 2: 1, 3: 1,4: 1,5: 1,6: 2,7: 2}, inplace=True)

In [54]:
df_depe['trainDensity'] = df['trainDensity'].map(lambda x: 1 if x>0 else 0)

In [55]:
categorical =['hour','date','rainfall','trainDensity']
for col in categorical:
    df_depe[col]=df_depe[col].astype('category')
#df_depe['rainfall']=df_depe['rainfall'].astype('category')

In [56]:
df_depe=pd.get_dummies(df_depe, drop_first=True)

In [57]:
df_depe.columns

Index(['busDensity', 'tramDensity', 'Cafe perc', 'Office perc', 'Shops perc',
       'mxi', 'recreationCount', 'campusCount', '5-14 %', '30-39 %', '40-49 %',
       '50-64 %', 'Population density 2021', 'min_temp', 'date_2', 'hour_2',
       'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8',
       'trainDensity_1', 'rainfall_1'],
      dtype='object')

In [58]:
scale= StandardScaler()

In [59]:
df_sc= scale.fit_transform(df_depe)
df_sc=pd.DataFrame(df_sc, columns=df_depe.columns)

In [60]:
y=df['tripDensity']
X=df_sc

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=24)

In [62]:
X_train.head()

,busDensity,tramDensity,Cafe perc,Office perc,Shops perc,mxi,recreationCount,campusCount,5-14 %,30-39 %,...,date_2,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,trainDensity_1,rainfall_1
21353,-0.033302,0.002249,0.901680,-0.124692,0.064567,0.641803,-0.196323,-0.109435,-0.848347,0.630044,...,-0.632456,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.377964,-0.377964,-0.165395,0.632456
3996,-0.359817,-0.461522,-1.517645,-0.326161,-0.184240,0.707316,-0.196323,-0.109435,-0.619524,-0.014719,...,-0.632456,-0.377964,-0.377964,-0.377964,2.645751,-0.377964,-0.377964,-0.377964,-0.165395,-1.581139
26811,-0.359817,-0.461522,-1.517645,-0.326161,-0.184240,0.707316,-0.196323,-0.109435,1.466699,0.188813,...,-0.632456,2.645751,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.165395,0.632456
28918,-0.359817,-0.461522,0.827507,-0.326161,-0.184240,0.273253,-0.196323,-0.109435,-0.765732,-0.838200,...,-0.632456,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.165395,0.632456
6953,-0.359817,-0.461522,0.952245,-0.223634,-0.184240,0.691151,0.988628,-0.109435,-0.738728,1.030244,...,-0.632456,-0.377964,-0.377964,-0.377964,-0.377964,2.645751,-0.377964,-0.377964,-0.165395,-1.581139

In [63]:
groups=df['SA1_CODE21'].unique()

In [64]:
model = mlm.MixedLM(y_train, X_train, groups=groups)

In [65]:
result=model.fit()

In [46]:
print(result.summary())

               Mixed Linear Model Regression Results
===================================================================
Model:                MixedLM    Dependent Variable:    tripDensity
No. Observations:     45427      Method:                REML
No. Groups:           338        Scale:                 0.0000
Min. group size:      1          Log-Likelihood:        393028.8036
Max. group size:      1          Converged:             Yes
Mean group size:      1.0
-------------------------------------------------------------------
                        Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------------
SA1_CODE21              15.825    0.510  31.001 0.000 14.825 16.826
busDensity              11.292    0.458  24.663 0.000 10.395 12.189
tramDensity             -1.712    0.489  -3.498 0.000 -2.671 -0.753
Cafe perc               12.044    0.392  30.731 0.000 11.275 12.812
Office perc              1.520    0.358   4.241 0.000  0.817  2.222
Shops perc               6.761    0.936   7.221 0.000  4.926  8.596
mxi                      3.961    0.373  10.632 0.000  3.231  4.691
recreationCount         -2.045    0.312  -6.549 0.000 -2.657 -1.433
campusCount             -1.624    0.396  -4.097 0.000 -2.401 -0.847
5-14 %                  -6.634    0.457 -14.519 0.000 -7.530 -5.739
30-39 %                  4.072    0.570   7.141 0.000  2.954  5.190
40-49 %                 -3.875    0.813  -4.767 0.000 -5.469 -2.282
50-64 %                  9.659    0.573  16.844 0.000  8.535 10.783
Population density 2021 -1.368    0.579  -2.363 0.018 -2.503 -0.233
min_temp                 6.300    0.472  13.357 0.000  5.376  7.225
date_2                   2.752    0.520   5.288 0.000  1.732  3.772
hour_2                   5.577    0.435  12.812 0.000  4.724  6.431
hour_3                  -1.789    0.494  -3.625 0.000 -2.756 -0.822
hour_4                   4.346    0.474   9.172 0.000  3.417  5.275
hour_5                   4.745    0.498   9.524 0.000  3.769  5.722
hour_6                   3.247    0.467   6.957 0.000  2.332  4.162
hour_7                  12.807    0.458  27.940 0.000 11.909 13.705
hour_8                  11.809    0.460  25.696 0.000 10.908 12.709
trainDensity_1           1.441    0.348   4.146 0.000  0.760  2.122
rainfall_1              -2.152    0.385  -5.594 0.000 -2.906 -1.398
Group Var               37.117 6387.041
===================================================================

In [66]:
print(result.summary())

               Mixed Linear Model Regression Results
===================================================================
Model:                MixedLM    Dependent Variable:    tripDensity
No. Observations:     45427      Method:                REML
No. Groups:           338        Scale:                 0.0000
Min. group size:      1          Log-Likelihood:        392553.0130
Max. group size:      1          Converged:             Yes
Mean group size:      1.0
-------------------------------------------------------------------
                        Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------------
busDensity              10.415    0.462  22.554 0.000  9.510 11.320
tramDensity              0.352    0.490   0.718 0.473 -0.609  1.312
Cafe perc               13.232    0.394  33.573 0.000 12.459 14.004
Office perc              1.673    0.362   4.620 0.000  0.963  2.382
Shops perc               4.389    0.943   4.655 0.000  2.541  6.237
mxi                      4.011    0.376  10.654 0.000  3.273  4.748
recreationCount         -1.992    0.315  -6.315 0.000 -2.611 -1.374
campusCount             -2.312    0.400  -5.780 0.000 -3.096 -1.528
5-14 %                  -4.610    0.457 -10.087 0.000 -5.506 -3.714
30-39 %                  4.801    0.576   8.339 0.000  3.673  5.930
40-49 %                  2.810    0.792   3.548 0.000  1.257  4.362
50-64 %                  2.444    0.530   4.615 0.000  1.406  3.482
Population density 2021  7.645    0.506  15.106 0.000  6.653  8.637
min_temp                 5.699    0.476  11.967 0.000  4.766  6.633
date_2                   2.821    0.526   5.363 0.000  1.790  3.852
hour_2                   5.441    0.440  12.368 0.000  4.579  6.303
hour_3                  -1.575    0.499  -3.159 0.002 -2.553 -0.598
hour_4                   3.821    0.479   7.985 0.000  2.883  4.759
hour_5                   5.930    0.502  11.813 0.000  4.946  6.914
hour_6                   3.954    0.471   8.394 0.000  3.031  4.877
hour_7                  12.059    0.463  26.071 0.000 11.153 12.966
hour_8                  11.313    0.464  24.376 0.000 10.404 12.223
trainDensity_1           1.885    0.351   5.371 0.000  1.197  2.573
rainfall_1              -1.782    0.389  -4.586 0.000 -2.543 -1.020
Group Var               37.902 6454.218
===================================================================

In [68]:
ypred=result.predict(X_test)

In [84]:
ypred

10411    -1.245392
43393   -44.519103
3391    -21.042020
23737   -21.327808
43043   -31.193034
           ...
22295    -1.852237
46469    -0.957658
12137     8.474422
45108   -11.821156
27044    10.879862
Length: 11357, dtype: float64

In [85]:
y_test

10411     28
43393      0
3391     254
23737      0
43043      0
        ...
22295      0
46469      0
12137    124
45108      0
27044     18
Name: tripDensity, Length: 11357, dtype: int64

In [70]:
print("MAE %f" %mean_absolute_error(y_test, ypred))

MAE 55.783067

In [92]:
print("MSE %f" %mean_squared_error(y_test, ypred))

MSE 22030.169061

In [96]:
mse=mean_squared_error(y_test, ypred)
rmse=round(np.sqrt(mse),2)
print("RMSE %f" %rmse)

RMSE 148.430000